---
- name: Playbook for staging
  hosts: staging
  become: yes
  roles:
    - { role: common, tags: common }
    - { role: git, tags: git }
    - { role: mysql, tags: mysql }
    - { role: nginx, tags: nginx }
    - { role: nodejs, tags: nodejs}
    - { role: ruby, tags: ruby }
    - { role: serverspec, tags: serverspec}

- name: Gathering Facts
  hosts: staging
  gather_facts: False
  tasks:
    - name: connection test
      ping: